[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = true
optimizer = true
evm_version = "istanbul"
optimizer_runs = 1_000_000
bytecode_hash = "none"

# [profile.uniswap]
# solc = "0.7.6"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config